# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Womak24 GmbH
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.womak24.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Navigation
navabout: Über uns
navleistungen: Dienstleistungen
navrisiko: "Risikoanalyse&nbsp;&amp; Beratung"
navimmo: Immobilienversicherungen
navmulti: "D&nbsp;&amp;&nbsp;O Multihaftpflichtversicherung"
navlohn: Lohnkostenoptimierung
navhonorar: Honorarberatung mit Nettotarifen
navweitere: Weitere Dienstleistungen
navquali: Qualitätssiegel
navnews: Onlinemagazin
navkontakt: Kontakt
navimpress: Impressum
navdata: Datenschutz
navwiederruf: Wiederrufsrecht
