# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Womak 24 GmbH Berlin – Brandenburg Versicherungsmakler
description: "Wir bieten Versicherungslösungen für Unternehmen in Berlin-Brandenburg. Hierbei überzeugen wir mit Qualifikation, Termintreue und Verlässlichkeit, was von unserer traditionell langjährigen Kundschaft sehr geschätzt wird. Sprechen Sie uns an – wir sind jederzeit für Sie da."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.womak24.de" # the base hostname & protocol for your site ... wird bei "jekyll serve" automatisch auf http://localhost:4000/ gesetzt

# Build settings
markdown: kramdown

# Navigation
navabout: Über uns
navleistungen: Dienstleistungen
navrisiko: "Risikoanalyse &amp; Beratung"
navimmo: Immobilienversicherungen
navmulti: "D &amp; O Multihaftpflichtversicherung"
navlohn: Lohnkostenoptimierung
navhonorar: Beratung Altersvorsorge
navweitere: Weitere Dienstleistungen
navquali: Qualität
navnews: Kundenmagazin
navkontakt: Kontakt
navimpress: Impressum
navfirstinfo: Erstinformation
navdata: Datenschutz
navwiderruf: Widerrufsrecht
navschaden: Schaden melden
navelsterwerda: Hauptsitz Elsterwerda
navberlin: Servicebüro Berlin

# Telephone Numbers
# change when needed as well in _posts/footer-kontakt, _posts/kontakt (md files)
telElsterwerda: +49 (0)3533 4826-0
faxElsterwerda: +49 (0)3533 4722
telBerlin: +49 (0)30 61202961
telJule: +49 (0)1522 4061421
telDIHK: +49 (0)180 60 05 85 0
faxDIHK: +49 (0)30 20308-1000
telCottbusIHK: +49 (0)355 365-0
faxCottbusIHK: +49 (0)355 365-266

#Emails
mailCottbusIHK: ihkcb@cottbus.ihk.de
mailInfocenterDIHK: infocenter@berlin.dihk.de
mailWomak: info@womak24.de
mailVermittlerregisterDIHK: vr@dihk.de

# Links
# change when needed as well in _posts/qualitaet (md file)
linkVema: https://www.vema-eg.de
linkBdvm: https://bdvm.de
# change maps in kontakt/berlin/index.html, kontakt/elsterwerda/index.html (md files)
linkHonorarkonzept: https://www.honorarkonzept.de
linkVermittlerregister: https://www.vermittlerregister.info
linkJulimage: https://julimage.de
linkBafin: https://www.bafin.de
linkEukommission: https://www.ec.europa.eu/consumers/odr
linkVersicherungsombudsmann: https://www.versicherungsombudsmann.de
linkBausparkassen: https://www.bausparkassen.de
linkPKVOmbudsmann: https://www.pkv-ombudsmann.de
linkOmbudsstelleInv: http://www.ombudsstelle-investmentfonds.de # TODO fix https?
linkSchlichtungsstelle: https://www.bundesbank.de/de/service/schlichtungsstelle
linkCottbusIHK: https://www.cottbus.ihk.de
linkEukommissionODR: https://webgate.ec.europa.eu/odr/main
linkGesetzeImI: https://www.gesetze-im-internet.de
linkLohnkonzepteH2: https://mehrgehalt.de/wie-funktionierts
linkLohnkonzepte: https://www.mehrgehalt.de
linkGoogleDatenschutz: https://policies.google.com/privacy?hl=de
linkGoogleReCaptcha : https://www.google.com/recaptcha/intro/v3.html
