# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Womak 24 GmbH Berlin – Brandenburg Versicherungsmakler
description: "Wir bieten Versicherungslösungen für Unternehmen in Berlin-Brandenburg. Hierbei überzeugen wir mit Qualifikation, Termintreue und Verlässlichkeit, was von unserer traditionell langjährigen Kundschaft sehr geschätzt wird. Sprechen Sie uns an – wir sind jederzeit für Sie da."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.womak24.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Navigation
navabout: Über uns
navleistungen: Dienstleistungen
navrisiko: "Risikoanalyse &amp; Beratung"
navimmo: Immobilienversicherungen
navmulti: "D &amp; O Multihaftpflichtversicherung"
navlohn: Lohnkostenoptimierung
navhonorar: Beratung Altersvorsorge
navweitere: Weitere Dienstleistungen
navquali: Qualität
navnews: Kundenmagazin
navkontakt: Kontakt
navimpress: Impressum
navfirstinfo: Erstinformation
navdata: Datenschutz
navwiderruf: Widerrufsrecht
navschaden: Schaden melden
navelsterwerda: Hauptsitz Elsterwerda
navberlin: Servicebüro Berlin
